name: geo_app
description: Geo Bangladesh App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_maps_flutter: ^2.5.3
  http: ^1.1.2
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  image: ^4.1.3
  location: ^5.0.3
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.1
  path: ^1.8.3
  provider: ^6.1.1
  dio: ^5.4.0
  mongo_dart: ^0.9.4
  sqflite: ^2.3.2
  http_parser: ^4.0.2
  # removed connectivity_plus

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/