name: geo_app
description: Geo Bangladesh App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.3.0
  http: ^0.13.5
  image_picker: ^0.8.9
  path_provider: ^2.0.15
  image: ^4.0.15
  location: ^4.4.0
  # connectivity_plus: ^5.0.1  <- REMOVE THIS LINE
  flutter_cache_manager: ^3.3.0
  shared_preferences: ^2.1.1
  cached_network_image: ^3.2.3
  path: ^1.8.2
  provider: ^6.0.5
  dio: ^5.1.2
  mongo_dart: ^0.9.1
  sqflite: ^2.2.8+4
  http_parser: ^4.0.2
  crypto: ^3.0.3

#  connectivity from pub dev is not working




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/